	environment(renderMultiDocument) <- environment()
	environment(multi_document) <- environment()
	environment(renderHTML) <- environment()
	environment(renderEPUB) <- environment()
	environment(renderPDF) <- environment()
	environment(renderDOCX) <- environment()